### ISSUE TITLE
Images for wikis

### ISSUE THREAD

**Issue by chrisogle** [smashgg/support#1]
![image](https://cloud.githubusercontent.com/assets/12819715/8245133/ce012ab2-15de-11e5-84ae-b6a331921803.png)

**Comment by chrisogle** [comment]
![image](https://cloud.githubusercontent.com/assets/12819715/8468173/0b19eb4a-2026-11e5-92d2-9e26e3dd812f.png)

**Comment by chrisogle** [comment]
![image](https://cloud.githubusercontent.com/assets/12819715/8468548/f2606a0c-202a-11e5-9a8a-2c7f0e3ab9ee.png)

**Comment by chrisogle** [comment]
![image](https://cloud.githubusercontent.com/assets/12819715/8468577/56d0ec64-202b-11e5-9093-7d8921014aa1.png)

**Comment by chrisogle** [comment]
![wiki-screenshots](https://cloud.githubusercontent.com/assets/12819715/8468610/b4a1ca2a-202b-11e5-9c4f-df074d9feb95.png)

**Comment by chrisogle** [comment]
![wiki-screenshots](https://cloud.githubusercontent.com/assets/12819715/8468651/2ec5c86a-202c-11e5-94bd-65ec4107d004.png)

**Comment by chrisogle** [comment]
![new-issue](https://cloud.githubusercontent.com/assets/12819715/8468656/44f0d012-202c-11e5-8f7f-da276bfa25ca.png)

**Comment by chrisogle** [comment]
![new-issue](https://cloud.githubusercontent.com/assets/12819715/8468953/89d9bc3a-2030-11e5-9fa4-33aada8826fb.png)

**Comment by chrisogle** [comment]
![wiki-screenshots](https://cloud.githubusercontent.com/assets/12819715/8469028/7edb9500-2031-11e5-9a1d-65db52d49662.png)

**Comment by chrisogle** [comment]
![new-issue](https://cloud.githubusercontent.com/assets/12819715/8469085/2d6d34de-2032-11e5-872d-e3c0355e2c2b.png)

**Comment by chrisogle** [comment]
![new-issue-page](https://cloud.githubusercontent.com/assets/12819715/8503037/0a19a0e0-2176-11e5-9c5f-1eeac9af7d7c.png)

**Comment by chrisogle** [comment]
![submit-issue](https://cloud.githubusercontent.com/assets/12819715/8503144/b398012e-2177-11e5-8e0f-4f5d005fa384.png)

**Comment by chrisogle** [comment]
![admin-click](https://cloud.githubusercontent.com/assets/12819715/8503234/8315a78e-2179-11e5-9a2d-0b011a592781.png)

**Comment by chrisogle** [comment]
![payments-click](https://cloud.githubusercontent.com/assets/12819715/8503257/0b815afa-217a-11e5-9fd1-8034c20ccc1e.png)

**Comment by chrisogle** [comment]
![image](https://cloud.githubusercontent.com/assets/12819715/8505181/6e45ebca-219c-11e5-8523-b063ee4774f4.png)

**Comment by chrisogle** [comment]
![processing-fee](https://cloud.githubusercontent.com/assets/12819715/8505559/e8368246-21a6-11e5-9b84-39272027bdd8.png)

**Comment by chrisogle** [comment]
![fee-on-registration](https://cloud.githubusercontent.com/assets/12819715/8505613/a115d6f8-21a8-11e5-90a1-deaf8dbd4c59.png)

**Comment by chrisogle** [comment]
![reg-settings](https://cloud.githubusercontent.com/assets/12819715/8519101/48a2fab4-238d-11e5-9bf3-4cc89b080bf9.png)

**Comment by chrisogle** [comment]
![reg-details](https://cloud.githubusercontent.com/assets/12819715/8519377/9a8fb6ee-238f-11e5-8f47-44231edbf6eb.png)

**Comment by chrisogle** [comment]
![custom-reg-details-box](https://cloud.githubusercontent.com/assets/12819715/8519607/1e8f1196-2391-11e5-8bb3-0163736aa0d7.png)

**Comment by chrisogle** [comment]
![venue-event-fees](https://cloud.githubusercontent.com/assets/12819715/8519987/b9e59c3a-2393-11e5-977b-6611b7bba6c6.png)

**Comment by chrisogle** [comment]
![attendee-agreements-reg](https://cloud.githubusercontent.com/assets/12819715/8531317/b9df57a8-23e3-11e5-866f-2d213afe9f02.png)

**Comment by chrisogle** [comment]
![attendee-agreements-reg](https://cloud.githubusercontent.com/assets/12819715/8531338/dbe3ab38-23e3-11e5-9647-55323e21f0d4.png)

**Comment by chrisogle** [comment]
![attendee-agreement-add](https://cloud.githubusercontent.com/assets/12819715/8531540/59492886-23e5-11e5-876b-69341f4f91db.png)

**Comment by chrisogle** [comment]
![add-attendee-button](https://cloud.githubusercontent.com/assets/12819715/8532360/e4f24638-23ea-11e5-8b48-584f54558eb2.png)

**Comment by chrisogle** [comment]
![check-box](https://cloud.githubusercontent.com/assets/12819715/8536245/fb7a6914-240b-11e5-8c71-167c447b257b.png)

**Comment by chrisogle** [comment]
![text-box](https://cloud.githubusercontent.com/assets/12819715/8536307/83363806-240c-11e5-80e2-7b59155644b4.png)

**Comment by chrisogle** [comment]
![number-box](https://cloud.githubusercontent.com/assets/12819715/8536336/f9eae3d4-240c-11e5-9750-6bb481a4d632.png)

**Comment by chrisogle** [comment]
![multiple-choice](https://cloud.githubusercontent.com/assets/12819715/8550066/85251b3a-248b-11e5-838f-f7098befa6e3.png)

**Comment by chrisogle** [comment]
![event-setup](https://cloud.githubusercontent.com/assets/12819715/8561425/701bef82-24e2-11e5-98de-a68b981c6961.png)

**Comment by chrisogle** [comment]
![edit-button](https://cloud.githubusercontent.com/assets/12819715/8566272/3fb364a0-251a-11e5-844f-ae63502a02d0.png)

**Comment by chrisogle** [comment]
![configure-phase-modal](https://cloud.githubusercontent.com/assets/12819715/8566297/758784f8-251a-11e5-9097-04bdfa00d8c4.png)

**Comment by chrisogle** [comment]
![phases-edit](https://cloud.githubusercontent.com/assets/12819715/8579159/382f0f30-2570-11e5-8dc3-2bbf7dd9d012.jpg)

**Comment by chrisogle** [comment]
![phases-edit](https://cloud.githubusercontent.com/assets/12819715/8579188/554a26ea-2570-11e5-977f-3ca9de70fd2a.jpg)

**Comment by chrisogle** [comment]
![seeding-page](https://cloud.githubusercontent.com/assets/12819715/8579666/34dd8714-2573-11e5-9a1f-d13e16dbf6bd.jpg)

**Comment by chrisogle** [comment]
![seeding-page](https://cloud.githubusercontent.com/assets/12819715/8579735/9843e690-2573-11e5-9386-5aa0cca37b50.jpg)

**Comment by chrisogle** [comment]
![seeding-slide-out](https://cloud.githubusercontent.com/assets/12819715/8581330/48b6b7ec-257d-11e5-8971-dabda062aa9c.jpg)

**Comment by chrisogle** [comment]
![manage-doubles](https://cloud.githubusercontent.com/assets/12819715/8584720/dc80918c-2596-11e5-8364-b59aff5f587a.jpg)

**Comment by chrisogle** [comment]
![image](https://cloud.githubusercontent.com/assets/12819715/8883243/8995507c-320a-11e5-8d17-f9f5374698e7.png)

**Comment by chrisogle** [comment]
![permissions](https://cloud.githubusercontent.com/assets/12819715/8883277/cda8769a-320a-11e5-9bdf-c5bc8d383e09.jpg)

**Comment by chrisogle** [comment]
![publishing](https://cloud.githubusercontent.com/assets/12819715/8966678/9ef1b06a-3600-11e5-87a1-ac1c8a7d1ae1.jpg)

**Comment by chrisogle** [comment]
![attendee-agreements2](https://cloud.githubusercontent.com/assets/12819715/8967869/c5bb3ebc-3607-11e5-91b1-d670868488ad.jpg)

**Comment by chrisogle** [comment]
![event-setup-2](https://cloud.githubusercontent.com/assets/12819715/8968091/3fec32a8-3609-11e5-8a6d-ebf1f03d125e.jpg)

**Comment by chrisogle** [comment]
![phase-edits](https://cloud.githubusercontent.com/assets/12819715/8968189/b0c682c6-3609-11e5-9c34-9c48cdefce69.jpg)

**Comment by chrisogle** [comment]
![on-site-payments](https://cloud.githubusercontent.com/assets/12819715/9342791/1dcbc708-45bb-11e5-9715-cb24f0b36a81.jpg)

**Comment by chrisogle** [comment]
![zendesk](https://cloud.githubusercontent.com/assets/12819715/13661030/7f8c6894-e64c-11e5-9350-b03707a2a89f.png)

**Comment by chrisogle** [comment]
![early-bird-shirt-sticker](https://cloud.githubusercontent.com/assets/12819715/13797285/0b4066ea-ead2-11e5-93c8-a364ea777d1c.png)

**Comment by chrisogle** [comment]
![shine-regular-shirt-for-reg](https://cloud.githubusercontent.com/assets/12819715/14539084/055526e0-023c-11e6-85cb-496e6349413b.png)

**Comment by chrisogle** [comment]
![braingear](https://cloud.githubusercontent.com/assets/12819715/15304204/301144c6-1b79-11e6-8b17-908e45bc834f.png)

**Comment by chrisogle** [comment]
![braingear](https://cloud.githubusercontent.com/assets/12819715/15305427/4a45059c-1b80-11e6-98b9-9e1ee0071a88.png)

**Comment by chrisogle** [comment]
![bg-smallest](https://cloud.githubusercontent.com/assets/12819715/15305651/88ce2130-1b81-11e6-9423-16cc51629770.png)

**Comment by chrisogle** [comment]
![black-shirt](https://cloud.githubusercontent.com/assets/12819715/15906853/e504c578-2d77-11e6-9b64-1c4639b83ba9.png)

**Comment by chrisogle** [comment]
![assignee](https://cloud.githubusercontent.com/assets/12819715/16113144/268aa232-3378-11e6-892b-769e5eacc19c.jpg)

**Comment by SFmindbender** [comment]
![of1](https://cloud.githubusercontent.com/assets/12941121/16136417/0f649d12-33df-11e6-9311-7ebedf0f724e.png)

**Comment by SFmindbender** [comment]
![of2](https://cloud.githubusercontent.com/assets/12941121/16136527/10259804-33e0-11e6-9874-69cb6214a890.png)

**Comment by SFmindbender** [comment]
![of3](https://cloud.githubusercontent.com/assets/12941121/16136601/cf988570-33e0-11e6-8739-c4d82df0d448.png)

**Comment by PoorZhu2** [comment]
![image](https://cloud.githubusercontent.com/assets/18316063/16137452/527349ba-33e8-11e6-935a-a4ad310262b0.png)

![image](https://cloud.githubusercontent.com/assets/18316063/16137479/a6f5853e-33e8-11e6-9591-40c71f224fe3.png)

![image](https://cloud.githubusercontent.com/assets/18316063/16137808/bc9cbf12-33eb-11e6-995d-8c208a5cd4a4.png)

**Comment by SFmindbender** [comment]
![of4](https://cloud.githubusercontent.com/assets/12941121/16139661/aeb0136e-33fe-11e6-9644-63ee32ff794b.png)

**Comment by SFmindbender** [comment]
![of5](https://cloud.githubusercontent.com/assets/12941121/16140556/bc3ca332-3406-11e6-8c75-37c920bdf733.png)
![of6](https://cloud.githubusercontent.com/assets/12941121/16140557/bc3fe8d0-3406-11e6-8448-b6fb802c778d.png)

**Comment by chrisogle** [comment]
![new-tournament](https://cloud.githubusercontent.com/assets/12819715/16147773/7587185a-3442-11e6-8988-29d8ecb35c4b.jpg)

**Comment by chrisogle** [comment]
![add-ticket](https://cloud.githubusercontent.com/assets/12819715/16148117/b8eb1d88-3444-11e6-8acf-1cb080f710cd.jpg)

**Comment by chrisogle** [comment]
![add-ticket](https://cloud.githubusercontent.com/assets/12819715/16148364/5de3e260-3446-11e6-96e3-c8e214e97e94.png)

**Comment by chrisogle** [comment]
![add-ticket](https://cloud.githubusercontent.com/assets/12819715/16148385/787d61f0-3446-11e6-941c-a8345398ff33.png)

**Comment by chrisogle** [comment]
![tournament-link](https://cloud.githubusercontent.com/assets/12819715/16148774/00da2040-3449-11e6-81e8-eebb2e5cf806.png)

**Comment by chrisogle** [comment]
![front-page](https://cloud.githubusercontent.com/assets/12819715/16179747/487d2bd6-363d-11e6-813e-cd2b3334fb7f.png)

**Comment by chrisogle** [comment]
![results-export](https://cloud.githubusercontent.com/assets/12819715/16180039/75b26e3c-3646-11e6-97e3-b27f3da884a8.png)

**Comment by SFmindbender** [comment]
![of9](https://cloud.githubusercontent.com/assets/12941121/16205835/8a51e68a-36da-11e6-9ae6-8aece1f98ee8.png)
![of8](https://cloud.githubusercontent.com/assets/12941121/16205834/8a51b188-36da-11e6-99af-5ce6fb4009f4.jpg)
![of7](https://cloud.githubusercontent.com/assets/12941121/16210263/0da220f8-36f0-11e6-88fe-81cb2d3e5164.jpg)

**Comment by PoorZhu2** [comment]
![image](https://cloud.githubusercontent.com/assets/18316063/16246136/be41cf80-37b8-11e6-88c4-6419fc6eea80.png)

![image](https://cloud.githubusercontent.com/assets/18316063/16246183/f8d9f582-37b8-11e6-84da-fb76cc3f6ab6.png)

**Comment by chrisogle** [comment]
![g4shirt](https://cloud.githubusercontent.com/assets/12819715/16254088/82e001e4-380a-11e6-8a1a-f67d546cbf2b.png)

**Comment by chrisogle** [comment]
![g4shirt](https://cloud.githubusercontent.com/assets/12819715/16254142/0c6a041e-380b-11e6-80bc-277589771c8a.png)
